// ignore_for_file: file_names

const List<Map<String, String>> dList = [
  {
    "name": "A형 간염",
    "operation": "3개월 후 가능(7일 이내 입원만)",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㄱ",
    "2nd_search": "ㄱ",
    "3rd_search": "ㄱ",
  },
  {
    "name": "각막염",
    "operation": "2년 내 불가",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㄱ",
    "2nd_search": "ㄱ",
    "3rd_search": "ㄱ",
  },
  {
    "name": "건초염",
    "operation": "2년 내 불가",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㄱ",
    "2nd_search": "ㄱ",
    "3rd_search": "ㄱ",
  },
  {
    "name": "결막염",
    "operation": "2년 내 불가",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㄱ",
    "2nd_search": "ㄱ",
    "3rd_search": "ㄱ",
  },
  {
    "name": "결절증",
    "operation": "2년 내 불가",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㄱ",
    "2nd_search": "ㄱ",
    "3rd_search": "ㄱ",
  },
  {
    "name": "골연화증",
    "operation": "2년 내 불가",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㄱ",
    "2nd_search": "ㄱ",
    "3rd_search": "ㄱ",
  },
  {
    "name": "과민성 대장증후군",
    "operation": "2년 내 불가",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㄱ",
    "2nd_search": "ㄱ",
    "3rd_search": "ㄱ",
  },
  {
    "name": "교통사고로 인한 2주이하 입원",
    "operation": "3개월 후 가능",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㄱ",
    "2nd_search": "ㄱ",
    "3rd_search": "ㄱ",
  },
  {
    "name": "구내염",
    "operation": "2년 내 불가",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㄱ",
    "2nd_search": "ㄱ",
    "3rd_search": "ㅇ",
  },
  {
    "name": "급성 부비동염",
    "operation": "3개월 후 가능(7일 이내 입원만)",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㄱ",
    "2nd_search": "ㅂ",
    "3rd_search": "ㅇ",
  },
  {
    "name": "급성 비인두염",
    "operation": "3개월 후 가능(7일 이내 입원만)",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㄱ",
    "2nd_search": "ㅂ",
    "3rd_search": "ㅇ",
  },
  {
    "name": "급성 인두염",
    "operation": "3개월 후 가능(7일 이내 입원만)",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㄱ",
    "2nd_search": "ㅇ",
    "3rd_search": "ㅇ",
  },
  {
    "name": "급성 편두염",
    "operation": "3개월 후 가능(7일 이내 입원만)",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㄱ",
    "2nd_search": "ㅍ",
    "3rd_search": "ㅇ",
  },
  {
    "name": "급성 방광염",
    "operation": "2년 내 불가",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㄱ",
    "2nd_search": "ㅂ",
    "3rd_search": "ㅇ",
  },
  {
    "name": "급성 신우신염",
    "operation": "2년 내 불가",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㄱ",
    "2nd_search": "ㅅ",
    "3rd_search": "ㅇ",
  },
  {
    "name": "급성 기관지염 (만성기관지염 제외)",
    "operation": "2년 내 불가",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㄱ",
    "2nd_search": "ㄱ",
    "3rd_search": "ㅇ",
  },
  {
    "name": "내향성손톱/내향성발톱/내향선손발톱수술",
    "operation": "3개월 후 가능",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㄴ",
    "2nd_search": "ㄴ",
    "3rd_search": "ㄴ",
  },
  {
    "name": "눈물샘 (누낭,누관,비루관)",
    "operation": "2년 내 불가",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㄴ",
    "2nd_search": "ㄴ",
    "3rd_search": "ㄴ",
  },
  {
    "name": "다래끼수술",
    "operation": "바로가능",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㄷ",
    "2nd_search": "ㄷ",
    "3rd_search": "ㄷ",
  },
  {
    "name": "다한증",
    "operation": "2년 내 불가",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㄷ",
    "2nd_search": "ㄷ",
    "3rd_search": "ㄷ",
  },
  {
    "name": "담석증으로 인한 담낭절제술",
    "operation": "3개월 후 가능",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㄷ",
    "2nd_search": "ㄷ",
    "3rd_search": "ㄷ",
  },
  {
    "name": "대장(결장) 용종제거술-수술1회한",
    "operation": "3개월후가능 (2년 1회한)",
    "2CI": "바로가능(횟수제한 없음)",
    "cancer": "3개월 후 가능(2년 1회한)",
    "1st_search": "ㄷ",
    "2nd_search": "ㄱ",
    "3rd_search": "ㅇ",
  },
  {
    "name": "두드러기",
    "operation": "2년 내 불가",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㄷ",
    "2nd_search": "ㄷ",
    "3rd_search": "ㄷ",
  },
  {
    "name": "디스크/추간판장애 - 목,허리 / 협착증",
    "operation": "2년 내 불가",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㄷ",
    "2nd_search": "ㅎ",
    "3rd_search": "ㅊ",
  },
  {
    "name": "리케챠병",
    "operation": "3개월 후 가능(7일 이내 입원만)",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㄹ",
    "2nd_search": "ㄹ",
    "3rd_search": "ㄹ",
  },
  {
    "name": "말라리아",
    "operation": "3개월 후 가능(7일 이내 입원만)",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅁ",
    "2nd_search": "ㅁ",
    "3rd_search": "ㅁ",
  },
  {
    "name": "매물치, 매복치",
    "operation": "2년 내 불가",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅁ",
    "2nd_search": "ㅁ",
    "3rd_search": "ㅁ",
  },
  {
    "name": "맹장수술, 충추 절제술",
    "operation": "3개월 후 가능",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅁ",
    "2nd_search": "ㅊ",
    "3rd_search": "ㅈ",
  },
  {
    "name": "모낭염",
    "operation": "2년 내 불가",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅁ",
    "2nd_search": "ㅁ",
    "3rd_search": "ㅁ",
  },
  {
    "name": "무릎질환 - 관절염, 염좌, 십자인대파열, 인공관절등",
    "operation": "2년 내 불가",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㄱ",
    "2nd_search": "ㅇ",
    "3rd_search": "ㅅ",
  },
  {
    "name": "무지외반증",
    "operation": "2년 내 불가",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅁ",
    "2nd_search": "ㅁ",
    "3rd_search": "ㅁ",
  },
  {
    "name": "발진푸스",
    "operation": "3개월 후 가능(7일 이내 입원만)",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅂ",
    "2nd_search": "ㅂ",
    "3rd_search": "ㅂ",
  },
  {
    "name": "백내장 수술",
    "operation": "3개월 후 가능",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅂ",
    "2nd_search": "ㅂ",
    "3rd_search": "ㅂ",
  },
  {
    "name": "볼거리/이하선염",
    "operation": "3개월 후 가능(7일 이내 입원만)",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅂ",
    "2nd_search": "ㅂ",
    "3rd_search": "ㅇ",
  },
  {
    "name": "부비동염(축농증) 수술",
    "operation": "3개월 후 가능(7일 이내 입원만)",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅂ",
    "2nd_search": "ㅊ",
    "3rd_search": "ㅊ",
  },
  {
    "name": "비문증",
    "operation": "2년 내 불가",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅂ",
    "2nd_search": "ㅂ",
    "3rd_search": "ㅂ",
  },
  {
    "name": "비염 수술",
    "operation": "3개월 후 가능",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅂ",
    "2nd_search": "ㅂ",
    "3rd_search": "ㅇ",
  },
  {
    "name": "비용종- 코 물혹",
    "operation": "2년 내 불가",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅂ",
    "2nd_search": "ㅇ",
    "3rd_search": "ㅁ",
  },
  {
    "name": "사고치료력 (재해, 상해등)",
    "operation": "2년 내 불가",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅅ",
    "2nd_search": "ㄱ",
    "3rd_search": "ㅈ",
  },
  {
    "name": "사마귀제거술",
    "operation": "바로가능",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅅ",
    "2nd_search": "ㅅ",
    "3rd_search": "ㅅ",
  },
  {
    "name": "사시수술",
    "operation": "3개월 후 가능",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅅ",
    "2nd_search": "ㅅ",
    "3rd_search": "ㅅ",
  },
  {
    "name": "상기도감염",
    "operation": "2년 내 불가",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅅ",
    "2nd_search": "ㅅ",
    "3rd_search": "ㅇ",
  },
  {
    "name": "서혜부탈장수술",
    "operation": "3개월 후 가능",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅅ",
    "2nd_search": "ㅅ",
    "3rd_search": "ㅌ",
  },
  {
    "name": "손가락수술, 발가락수술 (원인 재해에 한해)",
    "operation": "3개월 후 가능",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅅ",
    "2nd_search": "ㅂ",
    "3rd_search": "ㅈ",
  },
  {
    "name": "수근관 증후군 (팔목터널증후군) - 손목터널증후군",
    "operation": "2년 내 불가",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅅ",
    "2nd_search": "ㅍ",
    "3rd_search": "ㅌ",
  },
  {
    "name": "식중독",
    "operation": "3개월 후 가능(7일 이내 입원만)",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅅ",
    "2nd_search": "ㅅ",
    "3rd_search": "ㅅ",
  },
  {
    "name": "신장결석",
    "operation": "2년 내 불가",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅅ",
    "2nd_search": "ㅅ",
    "3rd_search": "ㄱ",
  },
  {
    "name": "쌍커풀수술, 안검내반수술",
    "operation": "3개월 후 가능",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅅ",
    "2nd_search": "ㅇ",
    "3rd_search": "ㅇ",
  },
  {
    "name": "아데노이드절제술",
    "operation": "3개월 후 가능",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅇ",
    "2nd_search": "ㅈ",
    "3rd_search": "ㅈ",
  },
  {
    "name": "아토피 피부염",
    "operation": "2년 내 불가",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅇ",
    "2nd_search": "ㅍ",
    "3rd_search": "ㅍ",
  },
  {
    "name": "안검하수",
    "operation": "2년 내 불가",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅇ",
    "2nd_search": "ㅇ",
    "3rd_search": "ㅇ",
  },
  {
    "name": "어깨병변/견관절탈구(오십견,어깨석회,어깨힘줄염증,어깨 회전근파열등)",
    "operation": "2년 내 불가",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅇ",
    "2nd_search": "ㅎ",
    "3rd_search": "ㅌ",
  },
  {
    "name": "연조직염/봉와직염",
    "operation": "2년 내 불가",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅇ",
    "2nd_search": "ㅂ",
    "3rd_search": "ㅂ",
  },
  {
    "name": "외모개선 목적 (미용수술, 성형수술)",
    "operation": "3개월 후 가능",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅁ",
    "2nd_search": "ㅅ",
    "3rd_search": "ㅅ",
  },
  {
    "name": "요관결석",
    "operation": "2년 내 불가",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅇ",
    "2nd_search": "ㄱ",
    "3rd_search": "ㄱ",
  },
  {
    "name": "요로결석",
    "operation": "2년 내 불가",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅇ",
    "2nd_search": "ㅇ",
    "3rd_search": "ㄱ",
  },
  {
    "name": "요실금 수술",
    "operation": "3개월 후 가능",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅇ",
    "2nd_search": "ㅇ",
    "3rd_search": "ㅇ",
  },
  {
    "name": "원인질환 없는 족저근막염 - 발바닥염증",
    "operation": "2년 내 불가",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅈ",
    "2nd_search": "ㅇ",
    "3rd_search": "ㅂ",
  },
  {
    "name": "위용종 제거술 - 수술1회한",
    "operation": "3개월 후 가능 (2년 1회한)",
    "2CI": "바로가능(횟수제한 없음)",
    "cancer": "3개월 후 가능(2년 1회한)",
    "1st_search": "ㅇ",
    "2nd_search": "ㅇ",
    "3rd_search": "ㅇ",
  },
  {
    "name": "유행성 출혈열",
    "operation": "3개월 후 가능(7일 이내 입원만)",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅇ",
    "2nd_search": "ㅊ",
    "3rd_search": "ㅊ",
  },
  {
    "name": "윤활막염 - 관절사이 염증",
    "operation": "2년 내 불가",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅇ",
    "2nd_search": "ㅇ",
    "3rd_search": "ㄱ",
  },
  {
    "name": "익상편 수술",
    "operation": "바로가능",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅇ",
    "2nd_search": "ㅇ",
    "3rd_search": "ㅇ",
  },
  {
    "name": "인플루엔자, 독감",
    "operation": "2년 내 불가",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅇ",
    "2nd_search": "ㄷ",
    "3rd_search": "ㄷ",
  },
  {
    "name": "임플란트, 치조골이식술",
    "operation": "바로가능",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅇ",
    "2nd_search": "ㅊ",
    "3rd_search": "ㅊ",
  },
  {
    "name": "자궁근종",
    "operation": "2년 내 불가",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅈ",
    "2nd_search": "ㄱ",
    "3rd_search": "ㄱ",
  },
  {
    "name": "장티푸스",
    "operation": "3개월 후 가능(7일 이내 입원만)",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅈ",
    "2nd_search": "ㅈ",
    "3rd_search": "ㅈ",
  },
  {
    "name": "장폐색, 장중첩",
    "operation": "2년 내 불가",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅈ",
    "2nd_search": "ㅈ",
    "3rd_search": "ㅈ",
  },
  {
    "name": "정계정맥류 - 고환",
    "operation": "2년 내 불가",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅈ",
    "2nd_search": "ㅈ",
    "3rd_search": "ㄱ",
  },
  {
    "name": "제왕절개술",
    "operation": "3개월 후 가능",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅈ",
    "2nd_search": "ㅈ",
    "3rd_search": "ㅈ",
  },
  {
    "name": "중이염",
    "operation": "2년 내 불가",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅈ",
    "2nd_search": "ㅈ",
    "3rd_search": "ㅇ",
  },
  {
    "name": "지방종 제거술",
    "operation": "3개월 후 가능(통원1회 또는 입원1일 / 2년내 1회 한함)",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅈ",
    "2nd_search": "ㅈ",
    "3rd_search": "ㅈ",
  },
  {
    "name": "직장 용종제거술 - 수술 1회한",
    "operation": "3개월 후 가능(2년 1회한)",
    "2CI": "바로가능(횟수제한 없음)",
    "cancer": "3개월 후 가능(2년 1회한)",
    "1st_search": "ㅈ",
    "2nd_search": "ㅇ",
    "3rd_search": "ㅇ",
  },
  {
    "name": "장염",
    "operation": "3개월 후 가능(7일 이내 입원만)",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅈ",
    "2nd_search": "ㅈ",
    "3rd_search": "ㅇ",
  },
  {
    "name": "쯔쯔가무시",
    "operation": "3개월 후 가능(7일 이내 입원만)",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅈ",
    "2nd_search": "ㅈ",
    "3rd_search": "ㅈ",
  },
  {
    "name": "치질(치핵,치루) 수술 (수술없는 입원은 인수불가)",
    "operation": "3개월 후 가능",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅊ",
    "2nd_search": "ㅊ",
    "3rd_search": "ㅊ",
  },
  {
    "name": "콜레라",
    "operation": "3개월 후 가능(7일 이내 입원만)",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅋ",
    "2nd_search": "ㅋ",
    "3rd_search": "ㅋ",
  },
  {
    "name": "크루프, 후두염",
    "operation": "2년 내 불가",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅋ",
    "2nd_search": "ㅎ",
    "3rd_search": "ㅎ",
  },
  {
    "name": "테니스엘보 - 팔부위 통증",
    "operation": "2년 내 불가",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅌ",
    "2nd_search": "ㅇ",
    "3rd_search": "ㅍ",
  },
  {
    "name": "티눈제거술",
    "operation": "바로가능",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅌ",
    "2nd_search": "ㅌ",
    "3rd_search": "ㅌ"
  },
  {
    "name": "편도절제술",
    "operation": "3개월 후 가능",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅍ",
    "2nd_search": "ㅍ",
    "3rd_search": "ㅍ"
  },
  {
    "name": "폐렴",
    "operation": "2년 내 불가",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅍ",
    "2nd_search": "ㅍ",
    "3rd_search": "ㅍ"
  },
  {
    "name": "피부열상봉합(=단순봉합) (근욱,혈관,힘줄,신경,인대 불가)",
    "operation": "바로가능",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅍ",
    "2nd_search": "ㅍ",
    "3rd_search": "ㅍ"
  },
  {
    "name": "피임목적 (정관수술, 난관결찰술)",
    "operation": "3개월 후 가능",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅍ",
    "2nd_search": "ㅍ",
    "3rd_search": "ㅍ"
  },
  {
    "name": "피지제거술 (피지낭종은 불가)",
    "operation": "바로가능",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅍ",
    "2nd_search": "ㅍ",
    "3rd_search": "ㅍ"
  },
  {
    "name": "하지정맥류/하지정맥류수술",
    "operation": "3개월 후 가능",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅎ",
    "2nd_search": "ㅎ",
    "3rd_search": "ㅎ"
  },
  {
    "name": "홍역",
    "operation": "3개월 후 가능(7일 이내 입원만)",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅎ",
    "2nd_search": "ㅎ",
    "3rd_search": "ㅎ"
  },
  {
    "name": "힘줄염-부위상관없음",
    "operation": "2년 내 불가",
    "2CI": "바로가능",
    "cancer": "바로가능",
    "1st_search": "ㅎ",
    "2nd_search": "ㅎ",
    "3rd_search": "ㅎ"
  }
];
